#!/bin/env bash
# vim:ft=bash

if [[ -z $1 ]]; then
  echo "please enter a valid tag or 'ALL'"
	exit 1
fi

case "$1" in
  ALL)
    ansible-playbook -i hosts -K setup.yaml --extra-vars "@variables.yaml"
    ;;
  *)
    ansible-playbook -i hosts -K --tags "$1" setup.yaml --extra-vars "@variables.yaml"
    ;;
esac
