- hosts: local
  vars:
    SOURCE_KEY: "./private/.ssh/ansible"
    DEST_KEY: "{{ lookup('env', 'HOME') }}/.ssh/ansible"
    USER: "{{ lookup('env', 'USER') or 'custom_user' }}"
    RELEASE_NAME: "focal"
    NERD_FONTS_VERSION: "v2.1.0"
    DEFAULT_ROFI_VERSION: "1.7.5"
    DEFAULT_TMUX_VERSION: "3.3a"
    GIT_NAME: "John Doe"
    GIT_EMAIL: "john@example.com"
  pre_tasks:
    - name: Update software
      become: true
      pacman:
        update_cache: true
        state: latest
      tags:
        - install
        - core
    - name: Printing all passed variables
      debug:
        msg: |
          Source key: {{ SOURCE_KEY }}
          Destination key: {{ DEST_KEY }}
          Release name: {{ RELEASE_NAME }}
          USER: {{ USER }}
          GIT Name: {{ GIT_NAME }}
          GIT Email: {{ GIT_EMAIL }}
          NerdFonts version: {{ NERD_FONTS_VERSION }}
          Rofi version: {{ DEFAULT_ROFI_VERSION }}
          Tmux version: {{ DEFAULT_TMUX_VERSION }}
            
  tasks:
    - include_tasks: tasks/ssh-setup.yaml
      tags:
        - install
        - ssh
    # TODO install all needed packages for arch too
    - include_tasks: tasks/core-setup.yaml
      tags:
        - install
        - ubuntu
        - core
    - include_tasks: tasks/languages-setup.yaml
      tags:
        - install
        - languages
        - go
        - php
        - rust
        - node
    - include_tasks: tasks/polybar-setup.yaml
      tags:
        - install
        - polybar
    - include_tasks: tasks/dunst-setup.yaml
      tags:
        - install
        - dunst
    - include_tasks: tasks/rofi-setup.yaml
      tags:
        - install
        - rofi
    - include_tasks: tasks/tmux-setup.yaml
      tags:
        - install
        - tmux
    - include_tasks: ./tasks/terminal-setup.yaml
      tags:
        - install
        - terminal
        - st
    - include_tasks: tasks/nvim-setup.yaml
      tags:
        - install
        - neovim
    - include_tasks: tasks/shell-setup.yaml
    - include_tasks: tasks/applications-setup.yaml
    - include_tasks: tasks/docker-setup.yaml
    - include_tasks: tasks/dotfiles-setup.yaml
    - include_tasks: private/setup.yaml
    - include_tasks: tasks/snap-setup.yaml
    - include_tasks: tasks/fonts-setup.yaml
      tags:
        - install
        - fonts
