- name: Install baapan
  shell: yarn global add baapan
  become: true
  become_user: "{{ USER }}"
  tags:
    - install
    - applications
    - baapan

- name: Install bitwarden cli
  shell: yarn global add @bitwarden/cli
  become: true
  become_user: "{{ USER }}"
  tags:
    - install
    - applications
    - bitwarden

- name: Install notion-enhanced
  become: true
  yay:
    name: notion-app-enhanced
    state: latest
    update_cache: yes
  tags:
    - install
    - applications
    - notion

- name: Install k8s lens
  become: true
  yay:
    name: lens
    state: latest
    update_cache: yes
  tags:
    - install
    - applications
    - lens

- name: Install insomnia
  become: true
  yay:
    name: insomnia
    state: latest
    update_cache: yes
  tags:
    - install
    - applications
    - insomnia
