- name: Install System Packages 1
  become: true
  pacman:
    name:
      - gettext
      - stow
      - openssl
      - libssl-dev
      - ca-certificates
      - curl
      - wget
      - git
    update_cache: true
  tags:
    - install
    - core

- name: Install System Packages 2
  become: true
  pacman:
    name:
      - ripgrep
      - fzf
    update_cache: true
  tags:
    - install
    - core

- name: Install System Packages 3
  become: true
  pacman:
    name:
      - lsof
      - ccache
      - nvidia-settings
      - pavucontrol
  tags:
    - install
    - core
