- name: Install docker
  become: true
  pacman:
    name: docker
    update_cache: true
    state: latest
  tags:
    - install
    - docker

- name: Add user to docker group
  become: true
  user:
    name: "{{ USER }}"
    group: "{{ USER }}"
    groups: docker
    append: true
  tags:
    - install
    - docker

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ DEFAULT_DOCKER_COMPOSE_VERSION }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
  tags:
    - install
    - docker
    - docker-compose
