- name: Clone dunst
  git:
    repo: 'https://github.com/k-vernooy/dunst.git'
    clone: true
    recursive: true
    dest: '/tmp/dunst'
  tags:
    - install
    - dunst

- name: Checkout to styling branch
  shell:
    chdir: /tmp/dunst
    cmd: 'git checkout progress-styling'
  tags:
    - install
    - dunst

- name: Build dunst
  make:
    chdir: /tmp/dunst
    params:
      WAYLAND: 0
  tags:
    - install
    - dunst

- name: Install dunst
  become: true
  make:
    chdir: /tmp/dunst
    target: install
    params:
      WAYLAND: 0
  tags:
    - install
    - dunst

- name: Clean up build
  become: true
  file:
    state: absent
    path: /tmp/dunst
  tags:
    - install
    - dunst
