- name: Install php
  become: true
  pacman:
    name:
      - php
  tags:
    - install
    - languages
    - php

- name: Install go
  become: true
  pacman:
    name:
      - go
      - go-tools
  tags:
    - install
    - languages
    - go

- name: Install rust
  shell:
    cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -q -y
  tags:
    - install
    - languages
    - rust

- name: Configure nightly rust
  shell: ". {{ lookup('env', 'HOME') }}/.cargo/env && rustup default nightly && rustup update"
  tags:
    - install
    - languages
    - rust

- name: Prepare n directory
  become: true
  file:
    path: "/usr/local/n"
    state: directory
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: 0755
    recurse: true
  tags:
    - install
    - languages
    - node

- name: Prepare n related directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ USER }}"
    group: "{{ USER }}"
    recurse: true
  loop:
    - /usr/local/bin
    - /usr/local/lib
    - /usr/local/include
    - /usr/local/share
  tags:
    - install
    - languages
    - node

- name: Install n
  get_url:
    url: https://raw.githubusercontent.com/tj/n/master/bin/n
    dest: "/usr/local/bin/n"
    mode: "u+x,g+x"
  tags:
    - install
    - languages
    - node

- name: Install nodejs
  shell:
    cmd: /usr/local/bin/n lts
  tags:
    - install
    - languages
    - node

- name: Install yarn
  shell:
    cmd: /usr/local/bin/npm i -g yarn
  tags:
    - install
    - languages
    - node
    - yarn

- name: Install pnpm
  shell:
    cmd: /usr/local/bin/npm i -g pnpm
  tags:
    - install
    - languages
    - node
    - pnpm
