- name: Install php
  become: true
  pacman:
    name:
      - php
  tags:
    - install
    - languages
    - php

- name: Install go
  become: true
  pacman:
    name:
      - go
      - go-tools
  tags:
    - install
    - languages
    - go

- name: Install rust
  shell:
    cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -q -y
  tags:
    - install
    - languages
    - rust

- name: Configure nightly rust
  shell: ". {{ lookup('env', 'HOME') }}/.cargo/env && rustup default nightly && rustup update"
  tags:
    - install
    - languages
    - rust

- name: Install n
  shell:
    cmd: curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
  tags:
    - install
    - languages
    - node

- name: Install nodejs
  shell:
    cmd: /usr/local/bin/n lts
  tags:
    - install
    - languages
    - node

- name: Install yarn
  shell:
    cmd: /usr/local/bin/npm i -g yarn
  tags:
    - install
    - languages
    - node
    - yarn
