- name: Add nodejs apt key
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  tags:
    - install
    - node

- name: Add nodejs ppa for apt repo
  become: true
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODE_VERSION }}.x {{ RELEASE_NAME }} main"
    update_cache: true
  tags:
    - install
    - node

- name: Install nodejs and npm
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    name: ["nodejs"]
  tags:
    - install
    - node

- name: npmjs prefix
  shell: mkdir -p ~/.local/.npm-global
  become: true
  become_user: "{{ USER }}"
  tags:
    - install
    - node

- name: add npmjs to path
  shell: PATH=~/.local/.npm-global/bin:$PATH
  become: true
  become_user: "{{ USER }}"
  tags:
    - install
    - node

- name: npmjs global settings
  shell: npm config set prefix '~/.local/.npm-global'
  become: true
  become_user: "{{ USER }}"
  tags:
    - install
    - node

- name: npmjs global settings export path in case dotfiles is not installed
  shell: export PATH=$PATH:~/.local/.npm-global/bin
  become: true
  become_user: "{{ USER }}"
  tags:
    - install
    - node
    - npm-path

- name: make cache folder and take ownership
  shell: "mkdir -p /usr/local/n && chown -R {{ USER }} /usr/local/n"
  become: true
  tags:
    - install
    - n
    - node

- name: make sure required directories exist
  shell: mkdir -p /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
  become: true
  become_user: "{{ USER }}"
  tags:
    - install
    - n
    - node

- name: take ownership of nodejs install destination directories
  shell: "chown -R {{ USER }} /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share"
  become: true
  tags:
    - install
    - n
    - node

- name: Install n
  npm:
    name: n
    global: yes
  become: true
  become_user: "{{ USER }}"
  tags:
    - install
    - node

- name: Install latest node using n
  shell: ~/.local/.npm-global/bin/n lts
  become: true
  become_user: "{{ USER }}"
  tags:
    - install
    - node
