- name: Download neovim binary
  become: true
  get_url:
      url: 'https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage'
      dest: '/usr/local/bin/nvim'
  tags:
    - download
    - neovim

- name: Make neovim executable
  become: true
  shell: chmod +x /usr/local/bin/nvim
  tags:
    - install
    - neovim
