- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim

- name: Clone Neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=Release -j 20"
  tags:
    - install
    - neovim

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=Release install"
  tags:
    - install
    - neovim
