- name: Install rofi
  become: true
  yay:
    name: rofi
    state: latest
    update_cache: yes
  tags:
    - install
    - rofi

- name: Install rofi-calc
  become: true
  yay:
    name: rofi-calc
    state: latest
    update_cache: yes
  tags:
    - install
    - rofi
    - rofi-calc
