- name: Install build dependencies
  become: true
  apt:
    name:
      - automake
      - autoconf
      - flex
      - bison
      - libpango1.0-dev
      - libglib2.0-dev
      - libgdk-pixbuf2.0-dev
      - libstartup-notification0-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-0
      - libxcb-xinerama0-dev
      - meson
      - libsystemd-dev
      - ninja-build
      - libdbus-1-dev
      - libinih-dev
      - libxcb-util-dev
      - libxcb-xkb-dev
      - libxcb-cursor-dev
      - libxkbcommon-x11-dev
      - libxcb-icccm4-dev
      - libxcb-randr0-dev
      - libxcb1-dev
      - check
      - libxcb-ewmh-dev
    update_cache: true
  tags:
    - install
    - rofi

- name: Get rofi
  unarchive:
    src: "https://github.com/davatorium/rofi/releases/download/1.7.2/rofi-1.7.2.tar.gz"
    remote_src: true
    dest: "/tmp/"
  tags:
    - install
    - rofi

- name: Build and install rofi
  become: true
  shell:
    chdir: /tmp/rofi-1.7.2
    cmd: meson setup build --prefix="/usr/bin" && ninja -C build && ninja -C build install
  tags:
    - install
    - rofi

- name: Copy rofi executable to bin
  become: true
  copy:
    src: "/tmp/rofi-1.7.2/build/rofi"
    dest: "/usr/bin/rofi"
    force: true
    mode: preserve
  tags:
    - install
    - rofi

- name: Clean up build
  become: true
  file:
    state: absent
    path: /tmp/rofi-1.7.2
  tags:
    - install
    - rofi

- name: Clean up apt
  become: true
  apt:
    autoremove: true
    update_cache: true
  tags:
    - install
    - rofi
