- name: Get rofi
  unarchive:
    src: "https://github.com/davatorium/rofi/releases/download/{{ DEFAULT_ROFI_VERSION }}/rofi-{{ DEFAULT_ROFI_VERSION }}.tar.gz"
    remote_src: true
    dest: "/tmp/"
  tags:
    - install
    - rofi

- name: Build and install rofi
  become: true
  shell:
    chdir: "/tmp/rofi-{{ DEFAULT_ROFI_VERSION }}"
    cmd: meson setup build --prefix="/usr/bin" && ninja -C build && ninja -C build install
  tags:
    - install
    - rofi

- name: Copy rofi executable to bin
  become: true
  copy:
    src: "/tmp/rofi-{{ DEFAULT_ROFI_VERSION }}/build/rofi"
    dest: "/usr/bin/rofi"
    force: true
    mode: preserve
  tags:
    - install
    - rofi

- name: Clean up build
  become: true
  file:
    state: absent
    path: "/tmp/rofi-{{ DEFAULT_ROFI_VERSION }}"
  tags:
    - install
    - rofi
