- name: Ensure .ssh directory exists
  become: true
  file:
    path: "{{ DEST_KEY | dirname }}"
    mode: 0700
    owner: "{{ USER }}"
    group: "{{ USER }}"
    state: directory
  tags:
    - install
    - ssh

- name: Install SSH key private
  become: true
  copy:
    src: "{{ SOURCE_KEY }}"
    dest: "{{ DEST_KEY }}"
    mode: 0600
    owner: "{{ USER }}"
    group: "{{ USER }}"
  tags:
    - install
    - ssh

- name: Install SSH key public
  become: true
  copy:
    src: "{{ SOURCE_KEY }}.pub"
    dest: "{{ DEST_KEY }}.pub"
    mode: 0644
    owner: "{{ USER }}"
    group: "{{ USER }}"
  tags:
    - install
    - ssh

- name: Set authorized key
  authorized_key:
    user: "{{ USER }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ DEST_KEY }}.pub"
  tags:
    - install
    - ssh
