- name: Remove current package
  apt:
    pkg: tmux
    state: absent
  become: true

- name: Install dependencies
  become: true
  apt:
    name:
      - tar
      - libevent-dev
      - libncurses-dev
  tags:
    - install
    - tmux

- name: Download source
  unarchive:
    src: 'https://github.com/tmux/tmux/releases/download/{{ DEFAULT_TMUX_VERSION }}/tmux-{{ DEFAULT_TMUX_VERSION }}.tar.gz'
    remote_src: true
    dest: '/tmp'
  tags:
    - install
    - tmux

- name: Prepare tmux build
  shell:
    cmd: './configure && make'
    chdir: /tmp/tmux-{{ DEFAULT_TMUX_VERSION }}
  tags:
    - install
    - tmux

- name: Install build
  become: true
  make:
    chdir: /tmp/tmux-{{ DEFAULT_TMUX_VERSION }}
    target: install
  tags:
    - install
    - tmux

- name: Move files
  become: true
  shell:
    cmd: 'sudo rm -rf /usr/local/src/tmux-* && mv /tmp/tmux-{{ DEFAULT_TMUX_VERSION }} /usr/local/src'
    warn: false
  tags:
    - install
    - tmux

- name: Check if TPM exists
  stat:
    path: /home/{{ USER }}/.tmux/plugins/tpm
  register: tpm_data
  tags:
    - install
    - tmux

- name: Install TPM
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    clone: true
    recursive: true
    dest: '/home/{{ USER }}/.tmux/plugins/tpm'
  when: not tpm_data.stat.exists
  tags:
    - install
    - tmux
